"""
Streamlit app to visualize the Collatz Conjecture.

The Collatz Conjecture states that for any positive integer n:
- If n is even, divide it by 2.
- If n is odd, multiply it by 3 and add 1.
- Repeat the process until n becomes 1.

This app allows users to input a number and visualize the sequence of steps
it takes to reach 1, along with the number of steps and the maximum value encountered.
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

plt.style.use("ggplot")


def collatz_sequence(n):
    """Generate the Collatz sequence for a given number n."""
    sequence = [n]
    while n != 1:
        if n % 2 == 0:
            n = n // 2
        else:
            n = 3 * n + 1
        sequence.append(n)
    return sequence


def plot_sequence(sequence):
    """Plot the Collatz sequence."""
    fig, ax = plt.subplots(figsize=(10, 5))
    ax.plot(sequence, marker='o', linestyle='-', color='b')
    ax.set_title("Collatz Conjecture Sequence")
    ax.set_xlabel("Step")
    ax.set_ylabel("Value")
    ax.grid(True)
    return fig


def main():
    st.title("Collatz Conjecture Explorer")
    st.write("""
    The Collatz Conjecture is a famous unsolved problem in mathematics.
    This app visualizes the sequence generated by the conjecture for any positive integer.
    """)

    # User input
    n = st.number_input("Enter a positive integer:", min_value=1, value=6)

    if st.button("Generate Sequence"):
        sequence = collatz_sequence(n)
        steps = len(sequence) - 1
        max_value = max(sequence)

        st.subheader(f"Collatz Sequence for n = {n}")
        st.write(f"Number of steps: {steps}")
        st.write(f"Maximum value: {max_value}")

        # Display the sequence as a table
        df = pd.DataFrame({"Step": range(len(sequence)), "Value": sequence})
        st.table(df)

        # Plot the sequence
        fig = plot_sequence(sequence)
        st.pyplot(fig)

    linkedin_url = "https://www.linkedin.com/in/bhavin-moriya-ph-d-b0b88b2/"
    github_url = "https://github.com/bhavinmoriya"
    youtube_url = "https://www.youtube.com/@bhavinmoriya9216"
    
    st.markdown("## Connect with me")
    
    col1, col2, col3  = st.columns(3)
    
    with col1:
        st.link_button("🔗 Follow on LinkedIn", linkedin_url)
    
    with col2:
        st.link_button("💻 Follow on GitHub", github_url)
    
    with col3:
        st.link_button("💻 Subscribe on YouTube", youtube_url)


if __name__ == "__main__":
    main()


linkedin_url = "https://www.linkedin.com/in/bhavin-moriya-ph-d-b0b88b2/"
github_url = "https://github.com/bhavinmoriya"
youtube_url = "https://www.youtube.com/@bhavinmoriya9216"
st.markdown("## Connect with me")

col1, col2, col3 = st.columns(3)

with col1:
    st.link_button("🔗 Follow on LinkedIn", linkedin_url)

with col2:
    st.link_button("💻 Follow on GitHub", github_url)

with col3:
    st.link_button("🔗 Subscribe on YouTube", youtube_url)
